title: Synapse Daily Digest
description: AI 策展的技术资讯日报
baseurl: ""
url: ""

sass:
  style: compressed

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - CNAME
  - vendor
